# Help system for GameTwo Development Environment

# Show WezTerm configuration for universal clickable just commands
help-wezterm-config:
    #!/usr/bin/env bash
    echo "🔧 WezTerm Configuration for Universal Clickable Just Commands"
    echo "============================================================="
    echo ""
    echo "✨ UNIVERSAL AUTO-DETECTION: Makes ANY 'just command' text clickable!"
    echo ""
    echo "Add this to your ~/.wezterm.lua config file:"
    echo ""
    echo "local wezterm = require 'wezterm'"
    echo "local config = {}"
    echo ""
    echo "-- Universal hyperlink rules for just commands"
    echo "config.hyperlink_rules = {"
    echo "  -- AUTO-DETECT: Make any 'just command-name [arguments]' text clickable"
    echo "  {"
    echo "    regex = '\\\\bjust ([a-zA-Z0-9._-]+(?:\\\\s+[^\\\\s#][^#]*?)??)(?=\\\\s*#|\\\\s*\$)',"
    echo "    format = 'just://\$1',"
    echo "    highlight = 1,"
    echo "  },"
    echo "  -- Keep existing URL support"
    echo "  {"
    echo "    regex = '\\\\b\\\\w+://\\\\S+[)/a-zA-Z0-9-_]',"
    echo "    format = '\$0',"
    echo "  },"
    echo "}"
    echo ""
    echo "-- Handle just:// protocol clicks"
    echo "wezterm.on('open-uri', function(window, pane, uri)"
    echo "  if uri:find('^just://') then"
    echo "    local cmd = uri:gsub('^just://', '')"
    echo "    window:perform_action("
    echo "      wezterm.action.SendString('just ' .. cmd .. '\\r'),"
    echo "      pane"
    echo "    )"
    echo "    return false"
    echo "  end"
    echo "  return true"
    echo "end)"
    echo ""
    echo "return config"
    echo ""
    echo "🎯 WHAT THIS ENABLES:"
    echo "✅ ALL help commands become clickable automatically"
    echo "✅ Commands WITH arguments: 'just logs test_123' → fully clickable"
    echo "✅ Quoted arguments: 'just test-android \\'system.*\\'' → fully clickable"
    echo "✅ Error messages with 'just validate-gdscript' become clickable"
    echo "✅ Documentation with any just commands → clickable"
    echo "✅ Future commands automatically supported"
    echo "✅ Zero maintenance required"
    echo ""
    echo "💡 After adding this config:"
    echo "1. Restart WezTerm"
    echo "2. Run ANY help command (just help-debug, just help-logs, etc.)"
    echo "3. Click any 'just' command to execute it!"

# Legacy non-interactive help (text-only fallback)
help-static:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "🚀 GameTwo Development Environment (Static)"
    echo "==========================================="
    echo "💡 Use 'just help' for interactive clickable commands!"
    echo ""
    echo "🏗️  SMART BUILD COMMANDS (Recommended)"
    echo "  just build-all-android           # Android smart rebuild (3-5 min, was 20+ min)"
    echo "  just build-all-ios               # iOS smart rebuild (3-5 min, was 20+ min)"
    echo "  just fastbuild-android           # Android fast build (30-60 sec) ⚡"
    echo "  just build-install-ios           # iOS rebuild & install (2-5 min, was 20+ min)"
    echo ""
    echo "🔥 FORCE REBUILD (When Needed)"
    echo "  just rebuild-all-android         # Force complete Android rebuild (30-40 min)"
    echo "  just rebuild-all-ios             # Force complete iOS rebuild (30-40 min)"
    echo "  just build-all-android force=yes # Alternative force rebuild syntax"
    echo "  just build-all-ios force=yes     # Alternative force rebuild syntax"
    echo ""
    echo "🚀 LAUNCH COMMANDS"
    echo "  just run-desktop                 # Desktop (shows session ID for test creation) 🚀"
    echo "  just run-android                 # Android debug (shows session ID)"
    echo "  just launch-android              # Launch existing Android app"
    echo ""
    echo "✅ VALIDATION & SYNTAX CHECKING"
    echo "  just validate                    # Complete validation (format + syntax + runtime) ⚡"
    echo "  just validate-gdscript           # Fast syntax validation (3 seconds)"
    echo "  just validate-godot              # Runtime validation (10-15 sec)"
    echo ""
    echo "📖 For full interactive help: just help"

# Universal clickable help system - all 'just' commands auto-clickable in WezTerm
help:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "🚀 GameTwo Development Environment"
    echo "=================================="
    echo "💡 Click any 'just' command below to execute it! (Auto-detected in WezTerm)"
    echo ""
    echo "🏗️  THREE-TIER BUILD SYSTEM"
    echo "  just build                       # Complete: source to device deployment (46 min) ⭐"
    echo "  just build-toolchain             # Foundation: editor + templates (40 min)"
    echo "  just build-artifacts             # Deployable files for all platforms (45 min)"
    echo "  just build-pipeline              # Complete: source to device deployment (46 min)"
    echo ""
    echo "🚀 PLATFORM-SPECIFIC PIPELINES"
    echo "  just build-pipeline-ios          # iOS: source to ready for device"
    echo "  just build-all-android           # Android smart rebuild (3-5 min)"
    echo "  just build-all-ios               # iOS smart rebuild (3-5 min)"
    echo ""
    echo "⚡ DEVELOPMENT COMMANDS"
    echo "  just fastbuild-android           # Android fast build (30-60 sec) ⚡"
    echo "  just build-install-ios           # iOS rebuild & install (30 sec)"
    echo "  just build-status                # Check what's built"
    echo ""
    echo "🔥 FORCE REBUILD (When Needed)"
    echo "  just rebuild-all-android         # Force complete Android rebuild (30-40 min)"
    echo "  just rebuild-all-ios             # Force complete iOS rebuild (30-40 min)"
    echo ""
    echo "📦 LEGACY BUILDS (Original Commands)"
    echo "  just build-all                   # Alias for build-toolchain"
    echo "  just quick-build-android         # Android APK + AAB (2-3 min)"
    echo "  just quick-build-ios             # iOS project (2-3 min)"
    echo ""
    echo "🚀 LAUNCH COMMANDS (Now with Session ID Display)"
    echo "  just run-desktop                 # Desktop (shows session ID for test creation) 🚀"
    echo "  just run-android                 # Android debug (shows session ID for test creation)"
    echo "  just launch-android              # Launch existing Android app"
    echo "  just launch-ios-iphone           # Launch existing iPhone app"
    echo "  just hotreload-ios-iphone        # iOS hot reload (5-10 sec) ✨"
    echo "  just restart-android-app         # Force restart Android app"
    echo ""
    echo "📱 SCREENSHOTS"
    echo "  just screenshot-android          # Quick screenshot for AI analysis"
    echo "  💡 Perfect for AI-assisted debugging and analysis"
    echo ""
    echo "🎬 TEST CREATION FROM GAMEPLAY (New Simplified Workflow)"
    echo "  just replay-generate SESSION_ID my-test  # One command: config + checksums!"
    echo "  💡 After run-desktop shows session ID, use this to create complete test"
    echo "  💡 Generated test includes automatic checksum validation"
    echo ""
    echo "🔧 CONFIG MANAGEMENT"
    echo "  just config-list                 # List available configs"
    echo "  💡 For detailed config workflows: just help-config"
    echo ""
    echo "🧪 TESTING"
    echo "  just test-android production-ready # Complete test suite"
    echo "  💡 For testing patterns & workflows: just help-debug"
    echo ""
    echo "📊 LOG ANALYSIS"
    echo "  just logs-errors-tagged TEST_ID  # Quick error scan (98% token savings)"
    echo "  just logs-last                   # Show most recent test run"
    echo "  💡 For detailed analysis: just help-logs"
    echo ""
    echo "📱 REAL-TIME ANDROID MONITORING"
    echo "  just android-logs-errors 30      # Live device error monitoring"
    echo "  just android-logs-status         # Check device & app status"
    echo "  💡 For complete device monitoring: just help-android-device-logs"
    echo ""
    echo "✅ VALIDATION & SYNTAX CHECKING"
    echo "  just validate                    # Complete validation (format + syntax + runtime) ⚡"
    echo "  just validate-gdscript           # Fast syntax validation (3 seconds)"
    echo "  just validate-godot              # Runtime validation (10-15 sec)"
    echo "  💡 For advanced validation workflows: just help-validation"
    echo ""
    echo "⚡ DAILY DEVELOPMENT WORKFLOW"
    echo "  just validate                    # 1. Complete validation (format + syntax + runtime)"
    echo "  just run-desktop                 # 2. Test locally (shows session ID)"
    echo "  just replay-generate SESSION_ID my-test  # 3. Create test (if needed)"
    echo "  just test-android 'system.*'    # 4. Test changes (30 sec)"
    echo "  just logs-errors-tagged TEST_ID  # 5. Debug issues (if any)"
    echo "  just fastbuild-android           # 6. Deploy changes (60 sec)"
    echo "  💡 For complete development workflows: just help-workflows"
    echo ""
    echo "🛠️  SETUP"
    echo "  just setup-android               # Setup Android environment"
    echo "  just build-editor                # Build custom Godot editor"
    echo "  💡 For complete setup guide: just help-build"
    echo ""
    echo "🔧 ADVANCED LOGGING"
    echo "  just runtime-filter-reset        # Reset log filters to defaults"
    echo "  💡 For complete logging control: just help-logs"
    echo ""
    echo "📖 DETAILED HELP"
    echo "  just help-timing                 # Platform timing comparison"
    echo "  just help-build                  # Build system architecture"
    echo "  just help-debug                  # Debug & testing guide"
    echo "  just help-logs                   # Log analysis & token efficiency"
    echo "  just help-android-device-logs    # 📱 NEW: Real Android device log monitoring"
    echo "  just help-workflows              # Common workflow patterns"
    echo "  just help-debug-modes            # 🚨 CRITICAL: run-* vs test-* for debug actions"
    echo "  just help-claude                 # Claude Code integration guide"
    echo ""
    echo "🖱️  TERMINAL FEATURES"
    echo "  just help-wezterm-config         # Setup guide for universal clickable commands"
    echo ""
    echo "📋 just --list  🔍 just show <cmd>  💡 All commands auto-clickable!"

# Note: Detailed help commands (help-android, help-ios, help-workflows, etc.) 
# are defined in the main justfile to avoid conflicts and maintain project-specific content
