extends Node

const SIGNAL_EVENT = "event"
enum GAME_STATE{START,DRAFT,PREPARE,PREBATTLE,BATTLE,POSTBATTLE}
enum EVENT_TYPE{test,UPDATE_DRAFT_AREA,REMOVE_BLOCK_FROM_DRAFT,UPGRADE,GAME_STATE_TRANSITION,DRAFT_ADD_BLOCK,REROLL_DRAFT,LINEUP_MERGE,DRAFT_MERGE,LINEUP_ADD_CARD,CARD_FINISHED_MOVING,CARD_MERGE_MOVE_FINISHED,MERGE_CARD_DONE,CARD_FINISHED_MOVING_TOP,ENEMY_LINEUP_ADD_CARD,DRAFT_COLOUMN_LOCKED,DRAFT_COLUMN_UNLOCKED,BATTLE,RESET_UNITS,CARD_STAT_CHANGE,TRIPPLE_TEST}

enum OBJECT_TYPE{TEST,CARD,CARD_HOLDER,BACKGROUND,BLOCK_LOCKED,BLOCK_UPGRADE,EMPTY_SPACE,BLOCK_NOSPACE,BLOCK_PASSTROUGH,BLOCK_ITEM}

var clicker = null
signal event

func _ready():
	print("core autoload ready")
